---
title: "Lista 1 - CP2"
author: "Davi Wentrick Feijó"
date: "2024-04-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Questão 1. Um programa de TV dura 1 hora, e um telespectador impaciente vai mudar de canal a qualquer momento durante o programa (Isso significa que o instante em que ele mudará de canal é uma variável aleatória $X \sim U[0,1]$.) Então considere a seguintes questões:

a) Qual a probabilidade dele assistir a maior parte do programa?

b) Se ele assistiu a maior parte do programa qual a probabilidade dele desligar a TV ou mudar de canal nos últimos 10 minutos?

Questão 2. Considere as variáveis aleatórias $X$ e $Y$ onde $X$ é discreta e $Y$ é contínua com distribuição conjunta dada por

$$
f(x, y)=\left\{\begin{array}{cc}
\frac{x y^{x-1}}{3}, & \text { se } x=1,2,3 \text { e } y \in[0,1] \\
0 & \text { caso contrário }
\end{array}\right.
$$




Calcule $F_{Y}(y \mid X=2)$ e $F_{X}(x \mid Y=1 / 2)$.

Nos sabemos que:

$$
F(y \mid X=2)=\frac{\mathbb{P}[Y=y, X=2]}{\mathbb{P}(X=2)}
$$


Vamos calcular $F_{Y}(y \mid X=2)$ 

$$
\begin{aligned}
& \mathbb{P}[X=2]=\int_0^1 \frac{2}{3} y^{2-1} \ \ dy =\frac{2}{3} \int_0^1 y \ \ dy =\left.\frac{2}{3} \frac{y^2}{2}\right|_0 ^1=\frac{1}{3} \\
\end{aligned}
$$

Obs: Trocamos $y$ por $t$ por clareza e evitar confundir com o $y$ da funcao

$$
\begin{aligned}
\mathbb{P}[Y \leq y,X=2] & =\int_0^y f(2, t) d t \\
& =\int_0^y \frac{2}{3} t^{2-1} d t \\
& =\frac{2}{3} \int_0^y t d t \\
& =\frac{y^2}{3}
\end{aligned}
$$

Podemos espeicifcar a funcao:

$$
\begin{aligned}

F(y \mid X=2) & =\frac{\mathbb{P}[y=y, x=2]}{\mathbb{P}(x=2)}\ 
= \begin{cases}0 & y \leqslant 0 \\
\frac{y^2}{3}/ \frac{1}{3} & 0<y \leqslant 1 \\
1 & y>1\end{cases}

= \begin{cases}0 & y \leqslant 0 \\
y^2 & 0<y \leqslant 1 \\
1 & y>1\end{cases}

\end{aligned}
$$

Para finalizar vamos calcular a $E(Y|X=2)$

$$
\begin{aligned}
E(y \mid x=2) & =\int_0^1 y \underbrace{d F_y(y \mid x=2)}_{2 y} \\
& =\int_0^1 2 y^2 d y=\frac{2}{3}
\end{aligned}
$$

Agora vamos calcular $F_{X}(x \mid Y=1 / 2)$ onde $x = k = 1,2,3$


$$
\begin{aligned}
F\left(x \left\lvert\, y=\frac{1}{2}\right.\right) & =\sum_{k=1}^{\min (3,[x])} f\left(k \left\lvert\, y=\frac{1}{2}\right.\right) \\
& =\sum_{k=1}^{\min (3,[x])} \frac{f\left(k, \frac{1}{2}\right)}{f_Y\left(\frac{1}{2}\right)}
\end{aligned}
$$


$$
\begin{aligned}
& f(k, y)=\frac{k \cdot y^{k-1}}{3} ; k=1,2,3 \\
& f_y\left(\frac{1}{2}\right)=f\left(1, \frac{1}{2}\right)+f\left(2, \frac{1}{2}\right)+f\left(3, \frac{1}{2}\right) \\
& =\frac{1 \frac{1}{2}^{1-1}}{3}+\frac{2 \frac{1}{2}^{2-1}}{3}+\frac{3 \frac{1}{2}^{3-1}}{3} \\
& =\frac{1}{3}+\frac{x \cdot \frac{1}{2}}{3}+\frac{3 \frac{1}{2}^2}{3} \\
& =\frac{1}{3}+\frac{1}{3}+\left(\frac{1}{2}\right)^2=\frac{2}{3}+\frac{1}{4}=\frac{11}{12} \\
& 
\end{aligned}
$$

$$
F\left(x \left\lvert\, y=\frac{1}{2}\right.\right)=\sum_{k=1}^{\operatorname{mm}(3,[x])} \frac{f\left(k, \frac{1}{2}\right)}{f_y\left(\frac{1}{2}\right)} =\left\{\begin{array}{l}
0, x<1 \\
1 \leq x<2 \\
2 \leq x<3 \\
x>3
\end{array}\right. 
$$



Questão 3. Sejam $X_{1}$ e $X_{2}$ variáveis aleatórias independentes, cada uma com distribuição geométrica dada por,

$$
\mathbb{P}\left[X_{1}=k\right]=\mathbb{P}\left[X_{2}=k\right]=p(1-p)^{k},=1,2, \ldots
$$

onde $0<p<1$. Então, calcule
a) $\mathbb{P}\left[X_{1}=X_{2}\right]$ e $\mathbb{P}\left[X_{1}<X_{2}\right]$;

b) Calcule a distribuição condicional de $X_{1}$ dado $X_{1}+X_{2}$;

Questão 4. Uma certa lâmpada tem uma vida em horas, tendo distribuição exponencial de parâmetro 1. Um jogador acende a lâmpada e, enquanto a lâmpada ainda estiver acesa, lança um dado equilibrado de 15 em 15 segundos. Qual o número esperado de $3^{\prime s}$ lançados pelo jogador até a lampada se apagar?

Questão 5. Seja $X$ e $Y$ variáveis aleatórias independentes tais que $X \sim \operatorname{Binom}(m, p)$ e $Y \sim \operatorname{Binom}(n, p)$. Obtenha a distribuição condicional de $X$ dada $X+Y$. Como se chama essa distribuição?

Questão 6. Sejam $Y \sim \operatorname{Exp}(1)$ e $(X \mid Y=y) \sim \operatorname{Poisson}(y)$. Mostre que

$$
\mathbb{P}[X=n]=1 / 2^{n+1}, n=0,1,2, \ldots
$$

$$
Z=(x \mid Y=y) \sim \text {Poisson}(y) \\
$$

$$
\mathbb{P}[Z=k]=\mathbb{P}[X=k \mid Y=y]=\frac{e^{-y} y^k}{k !}
$$

$$
\begin{aligned}
& \mathbb{P}[X=n]=\int_0^{\infty} \mathbb{P}[X=n | Y=y] f y(y) d y \\
& =\int_0^{\infty} \frac{e^{-y} y^n}{n !} e^{-y} d y \\
& =\frac{1}{n !} \int_0^{\infty} e^{-2 y} y^n d y \\
& =\frac{1}{n !} \int_0^{\infty} e^{-2 y}\left(\frac{2}{2} \cdot y^n\right) d y \\
\end{aligned}
$$

Vamos fazer por substituicao:

$$
u = 2y \\ \frac{du}{2} = dy
$$


$$
\begin{aligned}
& =\frac{1}{2^n n !} \int_0^{\infty} e^{-2 y}(2 y)^n \frac{d u}{2} \\
& =\frac{1}{2^n n !} \cdot \frac{1}{2} \underbrace{\int_0^{\infty} e^{-u} u^n d u}_{=\Gamma(n+1) = n!} \\
& =\frac{1}{2^{n+1}} \cdot \frac{n !}{n !}=\frac{1}{2^{n+1}} \\

\end{aligned}
$$



Questão 7. Um contador recebe impulsos de duas fontes independentes, $A$, e $B$. A fonte $A$ gera impulsos segundo um processo de Poisson com parâmetro $\lambda>0$, enquanto a fonte $B$ gera impulsos segundo um processo de Poisson com parâmetro $\xi>0$. Suponha que o contador registre todo o impulso gerado pelas duas fontes.

a) Seja $X_{t}$ o número de impulsos registrados até o tempo $t, t>0\left(X_{0}=0\right)$. Explique porque $\left\{X_{t}\right\}$ tem distribuição Poisson. Qual parâmetro?

b) Qual a probabilidade de que o primeiro impulso gerado seja da fonte $A$ ?

c) Dado que exatamente 100 impulsos foram contados durante a primeira unidade de tempo, qual a distribuição que você atribui ao número emitido pela fonte $A$ ?



d) Desde que exatamente 1 particula chegar ate o tempo $t>0$, qual a distribuicao condicional do seu tempo de chegada? $T_1|X_t = ?$

Vamos definir:

* $X_t$ = Numero de particulas que chegam até o tempo $t$ $\sim$ Poisson $(\lambda t)$

* $T_1$ = Tempo de chegada da 1 particula $\sim$ exp$(\lambda)$


$$
\begin{aligned}
F_X(X \mid A) & =\frac{\mathbb{P}[[X \leq x] \cap A]}{\mathbb{P}[A]} \\ 
F_{T_1}\left(X \mid X_t=1\right)&=\frac{P\left[X \leq x, X_t=1\right]}{\mathbb{P}\left[X_t=1\right]}
\end{aligned}
$$

Vamos estudar essa funcao em alguns intervalos:

* $X \leq 0$

$$
F_{T_1}\left(X \mid X_t=1\right) = 0
$$

* $X \geq t$

$$
\begin{aligned} \left[X_t=1\right] \subseteq\left[0<T_1 \leqslant t\right] &= \left[T_1 \leqslant x\right] \cap \left[X_t=1\right] \\ 
 &= F_{T_1}\left(X \mid X_t=1\right)=1
\end{aligned}
$$

* $0<x<t$

$\left[T_1 \leqslant x, X_t=1\right]$ é a particula chegar até o tempo $x$ ou nao chegar outra particula entre $x$ e $t$

$$
\begin{aligned}
\mathbb{P}\left[T_1 \leq x, X_t=1\right] & =\mathbb{P}\left[X_s=1, X_t-X_s=0\right] \\
& =\mathbb{P}\left[X_s=1\right] \cdot \mathbb{P}\left[X_t-X_s=0\right] \\
& =\lambda_s e^{-\lambda_s}(\lambda_{(t-x)})^0 \cdot e^{-\lambda_{(t-x)}} \\ 
& =\lambda_s e^{-\lambda_S} \cdot e^{-\lambda_{(t-x)}} \\
\end{aligned}
$$

$$
\begin{aligned}
F_{T_1}\left(X \mid X_t=1\right)=\frac{P\left[X \leq x, X_t=1\right]}{\mathbb{P}\left[X_t=1\right]} &=\frac{\lambda_s e^{-\lambda_S} \cdot e^{-\lambda_{(t-x)}}}{\lambda_s e^{-\lambda_S}} \\
&= e^{-\lambda_{(t-x)}} \\
&=\frac{x}{t}
\end{aligned}
$$

$F_{t_1}\left(x \mid x_t=1\right)= \begin{cases}0, & x \leqslant 0 \\ \frac{x}{t}, & 0<x<t \\ 1, & x \geq t\end{cases}$


notas: O professor fez essa mas eu copiei a reosulacao dele e ta muito estranha, nao sei se ele pulou coisas ou fez do jeito confuso dele, enfim no momento nao tenho tempo pra quebrar mais a cabeca nisso (tenho prova de CP2 em 47min)





