---
title: "Lista 2 - CP2"
author: "Davi Wentrick Feijó"
date: "2024-04-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Questão 1. 

Seja $X$ uma variável aleatória contínua dada por

$$
f(x)=\left\{\begin{array}{cc}
\frac{2}{x^{3}} & \text { se } x>1 \\
0 & \text { se } x<1
\end{array}\right.
$$

Considere o evento $B=[X \leq 2]$, então

#### a) calcule a função de distribuição condicional de $X$ dado $B$, cuja fórmula é,

$$
F_{X}(x \mid B)=\frac{\mathbb{P}([X \leq x] \cap[X \leq 2])}{\mathbb{P}[X \leq 2]}
$$


$$
f(x)=\left\{\begin{array}{l}
\frac{2}{x^3}, x>1 \\
0, x<1
\end{array} \quad B=[x \leqslant 2]\right.
$$

Sabemos que $F_X(x)$ é:

$$
F_X(x) = \int f_X(x) dx = -\frac{1}{x^2}
$$

$$
\begin{aligned}
F_X(x \mid B) & =\mathbb{P}[X \leq x \mid B] \\
& =\frac{\mathbb{P}[X \leq x, X \leq 2]}{\mathbb{P}[X \leq 2]} \\
&=\frac{\mathbb{P}[X \leq x] \cap[x \leq 2]}{\mathbb{P}[X \leq 2]}
\end{aligned}
$$

Vamos encontrar $\mathbb{P}[X \leq 2]$

$$
\begin{aligned}
\mathbb{P}[X \leq 2] & = F_X(2) \\
 & =\int_{-\infty}^2 f(x) d x \\
& =\int_1^2 \frac{2}{x^3} d x \\
& =2 \int_1^2 \frac{1}{x^3} \partial x=2 \int_1^2 x^{-3} d x \\
& =2 \int_{\frac{x^2}{-2}}^2 \partial x=2 \int-\frac{1}{2 x^2} d x \\
& = \frac{2}{2}\int_1^2-\frac{1}{x^2} \partial x=-\left.\frac{1}{x^2}\right|_1 ^2 \\
& = (-\frac{1}{2^2}) -(-\frac{1}{1^2}) \\
& = -\frac{1}{2^2} +\frac{1}{1^2} \\
& =-\frac{1}{2^2}+1 \\
& =1-\frac{1}{4}=\frac{3}{4}
\end{aligned}
$$

Em seguida temos que encontrar $\mathbb{P}[X \leq x, X \leq 2]$

$$
\begin{aligned} 
& \mathbb{P}[X \leq x, X \leq 2]=\left\{\begin{array}{l}\mathbb{P}[X \leq x]\\ \mathbb{P}[X \leq 2] \end{array}\right.   =\left\{\begin{array}{l}\mathbb{P}[x \leq x]=\int_1^x f(a) d a = \int_1^x-\frac{1}{a^2} d a \\ \mathbb{P}[x \leq 2]=\frac{3}{4}
\end{array}\right. \\ 
\end{aligned}
$$

Obs: Quando temos interesse em calcular uma probabilidade de 2 eventos acontecerem (no caso $\mathbb{P}[X \leq x,X \leq 2]$) nos temos interesse na intersecção dos 2 eventos. Nesse exemplo o unico intervalo onde os 2 eventos podem acontece (ou seja compartilham em comum) é no intervalo de $[1,2]$, onde quando $x<1$ temos $0$ e quando $x \geq 2$ é igual a $3/4$, vamos encontrar essa funcao de distribuicao:

$$
\mathbb{P}[x \leq x, x \leq 2] = \mathbb{P}[x \leq 2]
$$


Como sabemos os intervalos $[1,2]$ podemos especificar a funcao e descrever seus comportamento em relacao a os valores possiveis de $x$, mas antes temos que calcular a funcao no intervalo de $[1,x]$ ja sabendo que $(x < 2)$ entao:


$$
\begin{aligned} 
& \mathbb{P}[X \leq x, X \leq 2] =\left\{\begin{array}{l}0, x<1 \\ F_X(x), 1 \leq x<2 \\ F_X(2), x \geq 2\end{array}\right. 
\end{aligned}
$$
Vamos encontrar $F_X(x)$ (Obs: como ireamos integrar ate $x$ por questoes de claridade vamos mudar o $x = a$ da funcao e deixar o $x$ somente como limite de integracao)

$$
\begin{aligned}
& F_X(x) = \int_1^x \frac{2}{a^3} d a=\int_1^x-\frac{1}{a^2} d a=-\left.\frac{1}{a^2}\right|_1 ^x=-\frac{1}{x^2}+1  =1-\frac{1}{x^2}
\end{aligned}
$$

Obs: nos integramos ate $x$ e nao 2 pois quando chega em 2 é o limite do intervalo e apos isso tudo tera probabilidade igual a $3/4$

$$
\begin{aligned} 
& \mathbb{P}[X \leq x, X \leq 2]  =\left\{\begin{array}{l}0, x<1 \\ 1-\frac{1}{x^2}, 1 \leq x<2 \\ \frac{3}{4}, x \geq 2\end{array}\right. 
\end{aligned}
$$

Contudo nos queremos é a distribuicao da condicional, logo vamos dividir cada um dos intervalos por $\mathbb{P}[X \leq 2] = 3/4$

$$
\begin{aligned}
& F(x \mid B)=\left\{\begin{array}{l}0/\mathbb{P}[X \leq 2], x<1 \\ \left(1-\frac{1}{x^2}\right) /\mathbb{P}[X \leq 2] \\ \frac{3}{4}/\mathbb{P}[X \leq 2], x>3\end{array}\right. =\left\{\begin{array}{l}0, x<1 \\ \frac{4}{3}\left(1-\frac{1}{x^2}\right), 1 \leq x<2 \\ 1, x>3\end{array}\right.
\end{aligned}
$$
Com isso chegamos na funcao acumulada condicional


#### b) derivando a resposta obtida no item a) calcule a função de densidade condicional de $X$ dado $B$,

$$
f(x \mid B)=\frac{d}{d x} F_{X}(x \mid B)
$$
$$
\begin{aligned} 
& f(x | B)=\frac{\partial}{\partial x} F_X(x \mid B) \\ & =\frac{\partial}{\partial x} \frac{4}{3}\left(1-\frac{1}{x^2}\right) \\ & =\frac{4}{3} \frac{\partial}{\partial x}\left(1-\frac{1}{x^2}\right) \\ & =\frac{4}{3} \frac{\partial}{\partial x}(1)-\frac{\partial}{\partial x}\left(\frac{1}{x^2}\right) \\ & \frac{4}{3}\left(0-\frac{\partial}{\partial x}\left(x^{-2}\right)\right) \\ & \frac{4}{3}\left(0-\left(-2 x^{-3}\right)\right. \\ & \frac{4}{3}\left(0+\frac{2}{x^3}\right)=\frac{4}{3} \cdot \frac{2}{x^3}=\frac{8}{3 x^3} \\ 
\end{aligned}
$$

Agora podemos especificar a funcao de distribuicao condicional:

$$
\begin{aligned} 
& f(x \mid B)= \begin{cases}0, & x<1 \\ \frac{8}{3 x^3}, & 1 \leq x<2 \\ 0, & x \geqslant 2\end{cases} \\ 
\end{aligned}
$$

#### c) usando o item anterior calcule a esperança condicional de $X$ dado $B$,

$$
E(X \mid B)=\int_{-\infty}^{\infty} x f(x \mid B) d x
$$

$$
\begin{aligned} 
E(x \mid B) & =\int_{-\infty}^{\infty} x f(x \mid \beta) d x \\ 
& =\int_1^2 x \frac{8}{3 x^3} \partial x \\ & =\frac{8}{3} \int_1^2 \frac{x}{x^3} \partial x \\ 
& =\frac{8}{3} \int_1^2 x \cdot x^{-3} d x \\ & =\frac{8}{3} \int_1^2 x^{-2} d x \\ & =\frac{8}{3} \int_1^2 \frac{x^{-2+1}}{-2+1} \partial x \\ 
& =\frac{8}{3} \int_1^2 \frac{x^{-1}}{-1} \partial x \\ 
& =\left.\frac{8}{3}\left(-\frac{1}{x}\right)\right|_1 ^2 \\ 
& =-\left.\frac{8}{3 x}\right|_1 ^2 \\
& =-\frac{8}{3(2)}+\frac{8}{3(1)} \\
& = -\frac{8}{6}+\frac{8}{3} \\
& = \frac{-8 \cdot 3+6 \cdot 8}{6 \cdot 3} \\
&=\frac{48-24}{18} \\
& =\frac{24}{18} \div 6=\frac{4}{3}

\end{aligned}
$$

### Questão 2. 

Considere as variáveis aleatórias $X$ e $Y$ com densidade conjunta dada por

$$
f(x, y)=\frac{e^{\frac{-x}{y}} e^{-y}}{y}, \text { onde } 0<x<\infty, 0<y<\infty
$$

Então,

#### a) determine a densidade marginal $f_{Y}$;


$$
\begin{aligned}
f_Y(y) & =\int \frac{e^{-\frac{x}{y}} e^{-y}}{y} d x   \\
& =\frac{e^{-y}}{y} \int e^{-\frac{x}{y}} d x  \\
\end{aligned}
$$

$$
d x=-\frac{x}{y} \\ d u=-\frac{1}{y} d x \\ d x=-y d u

$$


$$
\begin{aligned}
& =\frac{e^{-y}}{y}-y \int e^u d u \\
& =-e^{-y} \cdot e^u& \\
&=-e^{-y}\left.e^{-\frac{x}{y}}\right|_0 ^{\infty} \\
&=-e^{-y}(-e^{-\frac{x}{y}}+e^{-\frac{0}{y}}) \\
&=-e^{-y}(\lim _{x \rightarrow \infty}(-e^{-\frac{x}{y}})+0) \\
&=-e^{-y}(1+0) \\
& =e^{-y}
\end{aligned}
$$



#### b) determine a densidade condicional $f(X \mid Y=y)$;


$$
\begin{aligned}
f(X \mid Y =y) &=\frac{f(x, y)}{f_Y(y)} \\
& =\frac{\frac{e^{-\frac{x}{y}} e^{-y}}{y}}{e^{-y}} \\
& =\frac{e^{-\frac{x}{y}} e^{-y}}{y} \cdot \frac{1}{e^{-y}} \\
&=\frac{e^{-\frac{x}{y}}}{y}
\end{aligned}
$$


#### c) calcule $\mathbb{P}[0<X<1 \mid Y=2]$;

$$
\begin{aligned}
& P[0<x<1 \mid y=2]=\frac{P[(0<x<1) \cap Y=2]}{P[Y=2]} \\
& \int f(X \mid Y=y) d x=\int f(X \mid Y=2) d x \\
& =\int_0^1 \frac{e^{-\frac{x}{2}}}{2} d x \\
& =\frac{1}{2} \int e^{-x / 2} d x \\
\end{aligned}
$$

$$
u=-\frac{x}{2} \\ d u=-\frac{1}{2} d x \\-2 d \mu=d x
$$

$$
\begin{aligned}


& =\frac{1}{2} \int e^u-2 \partial u \\
& =\frac{1}{2}-2 \int e^u d u \\
& =-\left.e^{-\frac{x}{2}}\right|_0 ^1 \\
& =-(e^{-\frac{1}{2}}-e^{-\frac{0}{2}}) \\
& =e^{-\frac{0}{2}}-e^{-\frac{1}{2}} \\
& =1-e^{-\frac{1}{2}} \\
&
\end{aligned}
$$


#### d) calcule a esperança condicional $E(X \mid Y)$.


$$
\begin{aligned}
E(X \mid Y) & =\int_{-\infty}^{\infty} x f(x) d x \\
& =\int x \frac{e^{-\frac{x}{y}}}{y} d x \\
& =\frac{1}{y} \int x e^{-\frac{x}{y}} d x \\
\end{aligned}
$$
Vamos resolver a integral:

$$
u = -\frac{x}{y} \\ x = - uy \\ d u=-\frac{1}{y} d x \\ -y d u=d x

$$


$$
\begin{aligned}
& = \int (-y u) e^u-y du \\
& =  y^2 \int u e^u d u \\
\end{aligned}
$$

Vamos resolver a nova integral formada:

$$
 \int u e^u d u \\
$$

É necessario integrar por partes:

$$
f = u \ \ \ \ \ \ \ g' = e^u
$$
$$
f' = 1 \ \ \ \ \ \ \ g = e^u
$$
Agora colocamos na formula:

$$
fg- \int f'g
$$


$$
\begin{aligned}
& = u e^u-\int e^u du \\
& =u e^u-e^u  \\
\end{aligned}
$$

Agora vamos substituindo de volta:

$$
\begin{aligned}
& =   y^2\int u e^u d u \\
& =y^2(u e^u-e^u)   \\
& =y^2u e^u-y^2e^u   \\
& =-y^2\frac{x}{y} e^{-\frac{x}{y}}-y^2e^{-\frac{x}{y}}   \\
& =-yx e^{-\frac{x}{y}}-y^2e^{-\frac{x}{y}}   \\
\end{aligned}
$$

$$
\begin{aligned}
 & =\frac{1}{y} \int x e^{-\frac{x}{y}} d x \\
 & =  \frac{1}{y}(-yx e^{-\frac{x}{y}}-y^2e^{-\frac{x}{y}} )  \\
 & =  (-\frac{1}{y}yx e^{-\frac{x}{y}}-\frac{1}{y}y^2e^{-\frac{x}{y}} )  \\
 & =  (-x e^{-\frac{x}{y}}-ye^{-\frac{x}{y}} )  \\
 & =  -(x+y)e^{-\frac{x}{y}}  \\

\end{aligned}
$$

Vamos avaliar no intervalo de $[0,\infty]$

$$
\begin{aligned}
-(x+y)e^{-\frac{x}{y}}|_0 ^\infty &= \lim _{x \rightarrow \infty}-(x+y)e^{-\frac{x}{y}} - (-(0+y)e^{-\frac{0}{y}}) \\
&= 0 +(0+y)1) \\
&= y \\
\end{aligned}
$$

### Questão 3. 

Considere as variáveis aleatórias $X$ e $Y$ com densidade conjunta dada por

$$
f_{X, Y}(x, y)=\left\{\begin{array}{cc}
x+y & \text { se } 0<x, y<1 \\
0 & \text { caso contrário }
\end{array}\right.
$$

Então,

#### a) determine as densidades marginais $f_{X}$ e $f_{Y}$;

$$
\begin{aligned}
f_X(x) & =\int_0^1 x+y d y \\
& =\int_0^1 x d y+\int_0^1 y d y \\
& =x \int_0^1 1 d y+\left.\frac{y^2}{2}\right|_0 ^1 \\
& =\left.x \cdot y\right|_0 ^1+\left.\frac{y^2}{2}\right|_0 ^1 \\
& =x \cdot(1-0)+\left(\frac{1^2}{2}-0\right) \\
& =x+\frac{1}{2} \\
&= \frac{2 x+1}{2} \\
\end{aligned}
$$

$$
f_Y(y)  =\frac{2 y+1}{2}
$$

#### b) determine as densidades condicionais $f(x \mid Y=y)$ e $f(y \mid X=x)$;

$$
f(x \mid y=y) :=\frac{f(x, y)}{f_y(y)} \\
$$

$$
\begin{aligned}
f(X \mid Y=y) & =\frac{f(x, y)}{f_Y(y)} \\
& =\frac{(x+y)}{\frac{2 y+1}{2}} \\
&=(x+y) \cdot \frac{2}{2 y+1} \\
& =\frac{2(x+y)}{2 y+1} \\
\end{aligned}
$$

$$
f(Y \mid X=x) =\frac{f(x, y)}{f_x(x)}=\frac{(x+y)}{\frac{2 x+1}{2}}=\frac{2(x+y)}{2 x+1}

$$

#### c) calcule as esperanças condicionais $E(X \mid Y)$ e $E(Y \mid X)$.




$$
\begin{aligned}
E(X \mid Y) & =\int x f(x \mid y) d x \\
& =\int x \frac{2(x+y)}{2 y+1} d x \\
& =\frac{2}{2 y+1} \int x( x+ y) d x \\
& =\frac{2}{2 y+1} \int  x^2+ y x   \ \ \ d x \\
& =\frac{2}{2 y+1}  \int  x^2+\int  y x  \ \ \ d x \\
& =\frac{2}{2 y+1} \int x^2+ y \int x \ \ \ d x \\
& =\frac{2}{2 y+1}\left( \frac{x^3}{3}+ y \frac{x^2}{ 2}\right) \\
& =\frac{ x^3}{3} \cdot \frac{2}{2 y+1}+y \frac{x^2}{ 2} \cdot \frac{2}{2 y+1} \\
& =\frac{2 x^3}{6 y+3}+\frac{y x^2}{2 y+1} \\
& =\frac{2 x^3+3 y x^2}{6 y+3}
\end{aligned}
$$

Vai ser a mesma coisa para $Y$ mudando o $X$ pelo $Y$

$$
E(Y \mid X=x)=\frac{2 y^3+3 x y^2}{6 x+3}
$$





